
#region contract
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Type created for JSON at <<root>>
[System.Runtime.Serialization.DataContractAttribute()]
public partial class Forecast
{
    [System.Runtime.Serialization.DataMemberAttribute()]
    public Coord coord;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Weather[] weather;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string @base;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Main main;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int visibility;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Wind wind;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Clouds clouds;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int dt;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Sys sys;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int timezone;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int id;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string name;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int cod;
}

// Type created for JSON at <<root>> --> coord
[System.Runtime.Serialization.DataContractAttribute(Name = "coord")]
public partial class Coord
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lon;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;
}

// Type created for JSON at <<root>> --> weather
[System.Runtime.Serialization.DataContractAttribute(Name = "weather")]
public partial class Weather
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int id;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string main;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string description;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string icon;
}

// Type created for JSON at <<root>> --> main
[System.Runtime.Serialization.DataContractAttribute(Name = "main")]
public partial class Main
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double temp;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double feels_like;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double temp_min;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double temp_max;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int pressure;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int humidity;
}

// Type created for JSON at <<root>> --> wind
[System.Runtime.Serialization.DataContractAttribute(Name = "wind")]
public partial class Wind
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int speed;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int deg;
}

// Type created for JSON at <<root>> --> clouds
[System.Runtime.Serialization.DataContractAttribute(Name = "clouds")]
public partial class Clouds
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public float all;
}

// Type created for JSON at <<root>> --> sys
[System.Runtime.Serialization.DataContractAttribute(Name = "sys")]
public partial class Sys
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int type;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int id;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string country;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int sunrise;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int sunset;
}

#endregion

