//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// Type created for JSON at <<root>>
[System.Runtime.Serialization.DataContractAttribute()]
public partial class Location
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string status;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string country;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string countryCode;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string region;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string regionName;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string city;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string zip;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public float lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public float lon;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string timezone;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string isp;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string org;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string @as;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string query;
}

